version: '3'

services:
  mongodb-connector:
    image: mongodb-connector:latest
    container_name: mongodb-connector

    environment:
      - ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
      - CAMUNDA_CONNECTOR_POLLING_ENABLED=false
      - CAMUNDA_CONNECTOR_WEBHOOK_ENABLED=false
      - OPERATE_CLIENT_ENABLED=false
      - MONGODB_HOST=host.docker.internal
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root

    networks:
      - camunda-platform_camunda-platform

networks:
  camunda-platform_camunda-platform:
    external: true  # Indicates that the network is defined externally